# create a user
POST http://localhost:5000/users
Content-Type: application/json

{
"name": "yoga",
"email": "yoga@gmail.com",
"password": "1922",
"confPassword": "1922",
"role": "user"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
"name": "admin",
"email": "admin@gmail.com",
"password": "123",
"confPassword": "123",
"role": "user"
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
"name": "halo",
"email": "halo@gmail.com",
"password": "123",
"confPassword": "123",
"role": "admin"
}


###
//get All user

GET http://localhost:5000/users

###
//get single data
GET http://localhost:5000/users/4298c8d1-34cd-4d75-bda7-ada76288ab44

###
//update user
PATCH http://localhost:5000/users/82c13d0a-3d0c-4afc-9301-2f61964d2587
Content-Type: application/json

{
"name": "adhit baru",
"email": "adhit@gmail.com",
"password": "",
"confPassword": "",
"role": "user"
}

###
//delete user
DELETE  http://localhost:5000/users/e13417e2-3d7b-49da-af43-03d0b2f7f893

###
//Login

POST http://localhost:5000/login
Content-Type: application/json

{
"email": "admin@gmail.com",
"password": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
"email": "yoga@gmail.com",
"password": "1922"
}

###
//me
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout

###
//get all pruduk
GET http://localhost:5000/products

###
//post data produk
POST http://localhost:5000/products
Content-Type: application/json

{

 "createdAt": "2022-10-26",
    "kematian": 2,
    "pakan": 1,
    "bobot": 1,

}

###
//get all pruduk
GET http://localhost:5000/admin





